# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20171010_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='status',
            new_name='is_active',
        ),
    ]
